<div class="card panel"><div class="card-body row g-3">
    <div class="col-md-6"><label class="form-label">{{ __('app.member') }}</label><select class="form-select" name="member_id" required>@foreach($members as $member)<option value="{{ $member->id }}" @selected(old('member_id', $loan->member_id ?? '') == $member->id)>{{ $member->member_id }} - {{ $member->name }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">{{ __('app.loan_type') }}</label><select class="form-select" name="loan_type_id" required>@foreach($loanTypes as $type)<option value="{{ $type->id }}" @selected(old('loan_type_id', $loan->loan_type_id ?? '') == $type->id)>{{ $type->name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">{{ __('app.application_no') }}</label><input class="form-control" name="application_number" value="{{ old('application_number', $loan->application_number ?? 'LOAN-'.now()->format('YmdHis')) }}" required></div>
    <div class="col-md-4"><label class="form-label">{{ __('app.application_date') }}</label><input type="date" class="form-control" name="application_date" value="{{ old('application_date', isset($loan) ? $loan->application_date?->format('Y-m-d') : now()->format('Y-m-d')) }}" required></div>
    <div class="col-md-4"><label class="form-label">{{ __('app.loan_amount') }}</label><input type="number" step="0.01" class="form-control" name="amount" value="{{ old('amount', $loan->amount ?? '') }}" required></div>
    <div class="col-md-4"><label class="form-label">{{ __('app.interest_rate') }}</label><input type="number" step="0.01" class="form-control" name="interest_rate" value="{{ old('interest_rate', $loan->interest_rate ?? '') }}" required></div>
    <div class="col-md-4"><label class="form-label">{{ __('app.installment_period') }}</label><input type="number" class="form-control" name="installment_period" value="{{ old('installment_period', $loan->installment_period ?? 12) }}" required></div>
    @isset($loan)
        <div class="col-md-4"><label class="form-label">{{ __('app.status') }}</label><select class="form-select" name="status"><option value="pending" @selected(old('status', $loan->status) === 'pending')>{{ __('app.pending') }}</option><option value="approved" @selected(old('status', $loan->status) === 'approved')>{{ __('app.approved') }}</option><option value="active" @selected(old('status', $loan->status) === 'active')>{{ __('app.active') }}</option><option value="rejected" @selected(old('status', $loan->status) === 'rejected')>{{ __('app.rejected') }}</option><option value="completed" @selected(old('status', $loan->status) === 'completed')>{{ __('app.completed') }}</option></select></div>
    @endisset
    <div class="col-12"><label class="form-label">{{ __('app.notes') }}</label><textarea class="form-control" rows="3" name="notes">{{ old('notes', $loan->notes ?? '') }}</textarea></div>
    <div class="col-12 d-flex gap-2"><button class="btn btn-primary">{{ __('app.save') }}</button><a class="btn btn-light" href="{{ route('loans.index') }}">{{ __('app.cancel') }}</a></div>
</div></div>
