@extends('layouts.app')
@section('title', __('app.sales_payments'))
@section('content')
<div class="row g-4 mb-4">
    <div class="col-md-4"><div class="card stat-card"><div class="card-body"><div class="text-muted">{{ __('app.total_sales') }}</div><h4>Rp {{ number_format($summary['total_sales'], 0) }}</h4></div></div></div>
    <div class="col-md-4"><div class="card stat-card"><div class="card-body"><div class="text-muted">{{ __('app.total_paid') }}</div><h4>Rp {{ number_format($summary['total_paid'], 0) }}</h4></div></div></div>
    <div class="col-md-4"><div class="card stat-card"><div class="card-body"><div class="text-muted">{{ __('app.outstanding') }}</div><h4>Rp {{ number_format($summary['total_balance'], 0) }}</h4></div></div></div>
</div>
<div class="d-flex justify-content-end mb-3"><a class="btn btn-primary" href="{{ route('sale-payments.create') }}">{{ __('app.add_payment') }}</a></div>
<div class="card panel"><div class="card-body table-responsive"><table class="table table-hover"><thead><tr><th>{{ __('app.invoice_number') }}</th><th>{{ __('app.member') }}</th><th>{{ __('app.sale_date') }}</th><th>{{ __('app.payment_date') }}</th><th>{{ __('app.sale_amount') }}</th><th>{{ __('app.payment_amount') }}</th><th>{{ __('app.remaining') }}</th><th>{{ __('app.status') }}</th><th></th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->invoice_number }}</td><td>{{ $payment->member->name }}</td><td>{{ $payment->sale_date->format('Y-m-d') }}</td><td>{{ $payment->payment_date->format('Y-m-d') }}</td><td>Rp {{ number_format($payment->sale_amount, 0) }}</td><td>Rp {{ number_format($payment->payment_amount, 0) }}</td><td>Rp {{ number_format($payment->remaining_balance, 0) }}</td><td><span class="badge text-bg-secondary">{{ ucfirst($payment->status) }}</span></td><td class="text-end d-flex gap-2 justify-content-end"><a class="btn btn-sm btn-outline-secondary" href="{{ route('sale-payments.show', $payment) }}">{{ __('app.view') }}</a><a class="btn btn-sm btn-outline-primary" href="{{ route('sale-payments.edit', $payment) }}">{{ __('app.edit') }}</a>@if(!auth()->user()->hasAnyRole(['member']))<form method="POST" action="{{ route('sale-payments.destroy', $payment) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" onclick="return confirm('{{ __('app.delete') }}?')">{{ __('app.delete') }}</button></form>@endif</td></tr>@empty<tr><td colspan="9" class="text-center text-muted">{{ __('app.no_sales_payments_found') }}</td></tr>@endforelse</tbody></table></div></div>
<div class="mt-3">{{ $payments->links() }}</div>
@endsection
