<div class="card panel"><div class="card-body row g-3">
    <div class="col-md-6"><label class="form-label">{{ __('app.member') }}</label><select class="form-select" name="member_id" required>@foreach($members as $member)<option value="{{ $member->id }}" @selected(old('member_id', $saving->member_id ?? '') == $member->id)>{{ $member->member_id }} - {{ $member->name }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">{{ __('app.savings_type') }}</label><select class="form-select" name="saving_type_id" required>@foreach($savingTypes as $type)<option value="{{ $type->id }}" @selected(old('saving_type_id', $saving->saving_type_id ?? '') == $type->id)>{{ $type->name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">{{ __('app.date') }}</label><input type="date" class="form-control" name="transaction_date" value="{{ old('transaction_date', isset($saving) ? $saving->transaction_date?->format('Y-m-d') : now()->format('Y-m-d')) }}" required></div>
    <div class="col-md-4"><label class="form-label">{{ __('app.transaction_type') }}</label><select class="form-select" name="transaction_type"><option value="deposit" @selected(old('transaction_type', $saving->transaction_type ?? 'deposit') === 'deposit')>{{ __('app.deposit') }}</option><option value="withdrawal" @selected(old('transaction_type', $saving->transaction_type ?? '') === 'withdrawal')>{{ __('app.withdrawal') }}</option></select></div>
    <div class="col-md-4"><label class="form-label">{{ __('app.amount') }}</label><input type="number" step="0.01" class="form-control" name="amount" value="{{ old('amount', $saving->amount ?? '') }}" required></div>
    <div class="col-12"><label class="form-label">{{ __('app.description') }}</label><textarea class="form-control" rows="3" name="description">{{ old('description', $saving->description ?? '') }}</textarea></div>
    <div class="col-12 d-flex gap-2"><button class="btn btn-primary">{{ __('app.save') }}</button><a class="btn btn-light" href="{{ route('savings.index') }}">{{ __('app.cancel') }}</a></div>
</div></div>
