@extends('layouts.app')
@section('title', __('app.my_transactions'))
@section('content')
<div class="row g-4 mb-4">
    <div class="col-md-4"><div class="card stat-card"><div class="card-body"><div class="text-muted">{{ __('app.sales_payments') }}</div><h4>{{ $summary['sales_count'] }}</h4><div>Rp {{ number_format($summary['sales_total'], 0) }}</div></div></div></div>
    <div class="col-md-4"><div class="card stat-card"><div class="card-body"><div class="text-muted">{{ __('app.savings') }}</div><h4>Rp {{ number_format($summary['savings_total'], 0) }}</h4><div>{{ __('app.balance') }}</div></div></div></div>
    <div class="col-md-4"><div class="card stat-card"><div class="card-body"><div class="text-muted">{{ __('app.installments') }}</div><h4>Rp {{ number_format($summary['installment_total'], 0) }}</h4><div>{{ __('app.total_paid') }}</div></div></div></div>
</div>

<div class="card panel mb-4"><div class="card-body"><h5>{{ __('app.sales_payments') }}</h5><div class="table-responsive"><table class="table"><thead><tr><th>{{ __('app.invoice_number') }}</th><th>{{ __('app.sale_date') }}</th><th>{{ __('app.payment_date') }}</th><th>{{ __('app.payment_method') }}</th><th>{{ __('app.payment_amount') }}</th><th>{{ __('app.remaining') }}</th><th>{{ __('app.status') }}</th></tr></thead><tbody>@forelse($salePayments as $payment)<tr><td>{{ $payment->invoice_number }}</td><td>{{ $payment->sale_date->format('Y-m-d') }}</td><td>{{ $payment->payment_date->format('Y-m-d') }}</td><td>{{ $payment->payment_method === 'cash' ? __('app.cash') : ($payment->payment_method === 'transfer' ? __('app.transfer') : __('app.payroll_deduction')) }}</td><td>Rp {{ number_format($payment->payment_amount, 0) }}</td><td>Rp {{ number_format($payment->remaining_balance, 0) }}</td><td>{{ __('app.'.$payment->status) }}</td></tr>@empty<tr><td colspan="7" class="text-center text-muted">{{ __('app.no_sales_payments_found') }}</td></tr>@endforelse</tbody></table></div></div></div>

<div class="card panel mb-4"><div class="card-body"><h5>{{ __('app.savings') }}</h5><div class="table-responsive"><table class="table"><thead><tr><th>{{ __('app.date') }}</th><th>{{ __('app.savings_type') }}</th><th>{{ __('app.transaction_type') }}</th><th>{{ __('app.amount') }}</th><th>{{ __('app.description') }}</th></tr></thead><tbody>@forelse($savings as $saving)<tr><td>{{ $saving->transaction_date->format('Y-m-d') }}</td><td>{{ $saving->savingType->name }}</td><td>{{ $saving->transaction_type === 'deposit' ? __('app.deposit') : __('app.withdrawal') }}</td><td>Rp {{ number_format($saving->amount, 0) }}</td><td>{{ $saving->description ?: '-' }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">{{ __('app.no_transactions_found') }}</td></tr>@endforelse</tbody></table></div></div></div>

<div class="card panel"><div class="card-body"><h5>{{ __('app.installments') }}</h5><div class="table-responsive"><table class="table"><thead><tr><th>{{ __('app.application_no') }}</th><th>{{ __('app.payment_date') }}</th><th>{{ __('app.installment_number') }}</th><th>{{ __('app.payment_amount') }}</th><th>{{ __('app.remaining') }}</th></tr></thead><tbody>@forelse($installments as $installment)<tr><td>{{ $installment->loan->application_number }}</td><td>{{ $installment->payment_date->format('Y-m-d') }}</td><td>{{ $installment->installment_number }}</td><td>Rp {{ number_format($installment->payment_amount, 0) }}</td><td>Rp {{ number_format($installment->remaining_balance, 0) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">{{ __('app.no_installment_payments_found') }}</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
